/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as rwaTokenSol from "./RwaToken.sol";
export { PropertyRegistry__factory } from "./PropertyRegistry__factory";
