/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rwaTokenSol from "./RwaToken.sol";
export type { rwaTokenSol };
export type { PropertyRegistry } from "./PropertyRegistry";
